# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title: "Pierre Carrillo"
description: "Pierre Carrillo's personal website"
author: "Pierre Carrillo"
